name: Build VST3 for Windows

on:
  workflow_dispatch:  # Можно запускать вручную
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    name: Build VST3 on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive  # Чтобы подтянуть JUCE

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: "3.26.4"

      - name: Configure CMake
        run: |
          cmake -B build -S . -G "Visual Studio 17 2022" ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DJUCE_ENABLE_PLUGIN_FORMAT_VST3=ON ^
            -DJUCE_BUILD_EXAMPLES=OFF ^
            -DJUCE_BUILD_DOCUMENTATION=OFF

      - name: Build Plugin
        run: cmake --build build --config Release

      - name: Upload VST3 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DroneSynth-Windows-VST3
          path: |
            build/DroneSynth_artefacts/Release/*.vst3
