name: Build DroneSynth (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # 2. Установка Visual Studio с нужными компонентами
      - name: Install Visual Studio
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: '17.0'  # VS2022
          components: 'Microsoft.VisualStudio.Component.VC.Tools.x86.x64;Microsoft.VisualStudio.Workload.NativeDesktop'

      # 3. Установка CMake
      - name: Install CMake
        shell: pwsh
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y --no-progress
          if ($LASTEXITCODE -ne 0) { throw "CMake install failed" }
          cmake --version

      # 4. Установка VST3 SDK
      - name: Setup VST3 SDK
        shell: pwsh
        run: |
          if (!(Test-Path "externals/VST3_SDK")) {
            New-Item -ItemType Directory -Path "externals" -Force | Out-Null
            git clone --recursive https://github.com/steinbergmedia/vst3sdk.git externals/VST3_SDK
          }

      # 5. Настройка окружения
      - name: Setup environment
        shell: pwsh
        run: |
          # Добавляем MSBuild в PATH
          $vsPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -version 17.0 -property installationPath
          $msbuildPath = Join-Path $vsPath "MSBuild\Current\Bin"
          Add-Content $env:GITHUB_PATH "$msbuildPath"

          # Проверяем доступность инструментов
          msbuild /version
          cmake --version

      # 6. Конфигурация CMake
      - name: Configure CMake
        shell: pwsh
        run: |
          cmake -B build `
            -DCMAKE_BUILD_TYPE=Release `
            -DJUCE_DIR="${{ github.workspace }}\externals\JUCE" `
            -DVST3_SDK_DIR="${{ github.workspace }}\externals\VST3_SDK"

      # 7. Сборка плагина
      - name: Build
        run: cmake --build build --config Release --target DroneSynth_VST3

      # 8. Загрузка артефактов
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DroneSynth_Windows
          path: |
            build/DroneSynth_artefacts/Release/VST3/DroneSynth.vst3
            build/DroneSynth_artefacts/Release/Standalone/DroneSynth.exe
