name: Windows Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # 1. Checkout with submodules
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # 2. Clean build directory
      - name: Clean workspace
        shell: pwsh
        run: |
          Remove-Item -Recurse -Force build, externals/VST3_SDK -ErrorAction SilentlyContinue
          New-Item -ItemType Directory -Path build | Out-Null

      # 3. Install CMake
      - name: Install CMake
        shell: pwsh
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y --no-progress
          cmake --version

      # 4. Install Visual Studio Build Tools
      - name: Setup MSVC Build Tools
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          vsversion: 2022
          toolset: 14.37 # укажем конкретную версию, чтобы избежать ошибки "Toolset 'latest' not found"

      # 5. Install VST3 SDK (очищаем если есть)
      - name: Get VST3 SDK
        shell: pwsh
        run: |
          Remove-Item -Recurse -Force externals/VST3_SDK -ErrorAction SilentlyContinue
          git clone --depth 1 --recursive https://github.com/steinbergmedia/vst3sdk.git externals/VST3_SDK

      # 6. Configure CMake
      - name: CMake Configure
        shell: pwsh
        run: |
          cmake -B build `
            -G "Visual Studio 17 2022" `
            -A x64 `
            -DCMAKE_BUILD_TYPE=Release `
            -DVST3_SDK_DIR="${{ github.workspace }}/externals/VST3_SDK" `
            -DJUCE_DIR="${{ github.workspace }}/externals/JUCE"

      # 7. Build Plugin
      - name: CMake Build
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          try {
            cmake --build build --config Release --target DroneSynth_VST3 -- /m
          } catch {
            Write-Host "##[error]Build failed!"
            if (Test-Path "${{ github.workspace }}/build/CMakeFiles/CMakeOutput.log") {
              Get-Content "${{ github.workspace }}/build/CMakeFiles/CMakeOutput.log" -Tail 50
            }
            throw $_
          }

      # 8. Upload artifacts
      - name: Upload VST3 and Standalone
        uses: actions/upload-artifact@v4
        with:
          name: DroneSynth-Windows
          path: |
            build/DroneSynth_artefacts/Release/VST3/DroneSynth.vst3
            build/DroneSynth_artefacts/Release/Standalone/DroneSynth.exe
