name: Build DroneSynth (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Клонирование репозитория с сабмодулями
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # 2. Установка зависимостей
      - name: Install dependencies (CMake, VS, Workload)
        shell: pwsh
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          if ($LASTEXITCODE -ne 0) { throw "CMake install failed" }

          choco install visualstudio2022community -y --no-progress --ignore-reboot
          if ($LASTEXITCODE -ne 0) { throw "VS install failed" }

          choco install visualstudio2022-workload-nativedesktop -y --no-progress --ignore-reboot
          if ($LASTEXITCODE -eq 3010) {
            Write-Host "Reboot required — skipping reboot in CI"
          } elseif ($LASTEXITCODE -ne 0) {
            throw "Workload install failed with code $LASTEXITCODE"
          }

          refreshenv

      # 3. Установка VST3 SDK
      - name: Setup VST3 SDK
        shell: pwsh
        run: |
          if (!(Test-Path "externals")) {
            New-Item -ItemType Directory -Path "externals" | Out-Null
          }

          git clone --recursive https://github.com/steinbergmedia/vst3sdk.git externals/VST3_SDK

      # 4. Конфигурация CMake
      - name: Configure CMake
        run: >
          cmake -B build
          -DCMAKE_BUILD_TYPE=Release
          -DJUCE_DIR=${{ github.workspace }}\externals\JUCE
          -DVST3_SDK_DIR=${{ github.workspace }}\externals\VST3_SDK

      # 5. Сборка плагина
      - name: Build
        run: cmake --build build --config Release --target DroneSynth_VST3

      # 6. Загрузка артефактов
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DroneSynth_Windows
          path: |
            build/DroneSynth_artefacts/Release/VST3/DroneSynth.vst3
            build/DroneSynth_artefacts/Release/Standalone/DroneSynth.exe
