name: Windows Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install dependencies
        shell: pwsh
        run: |
          choco install visualstudio2022community -y --no-progress
          choco install visualstudio2022-workload-nativedesktop -y --ignore-checksums --no-progress
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y --no-progress
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          refreshenv

      - name: Get VST3 SDK
        shell: pwsh
        run: |
          git clone --depth 1 --recursive https://github.com/steinbergmedia/vst3sdk.git externals/VST3_SDK

      - name: Get JUCE
        shell: pwsh
        run: |
          git clone --depth 1 https://github.com/juce-framework/JUCE.git externals/JUCE

      - name: Configure CMake
        shell: pwsh
        run: |
          cmake -B build `
            -G "Visual Studio 17 2022" `
            -A x64 `
            -DCMAKE_BUILD_TYPE=Release `
            -DVST3_SDK_DIR="${{ github.workspace }}/externals/VST3_SDK" `
            -DJUCE_DIR="${{ github.workspace }}/externals/JUCE"

      - name: Build
        shell: pwsh
        run: |
          cmake --build build --config Release --target DroneSynth_VST3 -- /m

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DroneSynth-Windows
          path: |
            build/DroneSynth_artefacts/Release/VST3/DroneSynth.vst3
            build/DroneSynth_artefacts/Release/Standalone/DroneSynth.exe
