name: Build DroneSynth (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # 2. Установка зависимостей
      - name: Install dependencies
        shell: pwsh
        run: |
          # Установка CMake
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y --no-progress
          if ($LASTEXITCODE -ne 0) { throw "CMake install failed" }

          # Установка Visual Studio с игнорированием кода 3010
          choco install visualstudio2022community -y --no-progress
          if ($LASTEXITCODE -ne 0 -and $LASTEXITCODE -ne 3010) { 
            throw "VS install failed with code $LASTEXITCODE" 
          }

          # Установка Workload с явной обработкой кода 3010
          choco install visualstudio2022-workload-nativedesktop -y --no-progress
          if ($LASTEXITCODE -eq 3010) {
            Write-Host "Reboot required but skipped in CI environment"
          } elseif ($LASTEXITCODE -ne 0) {
            throw "Workload install failed with code $LASTEXITCODE"
          }

          # Альтернативное обновление переменных среды
          $env:PATH = [System.Environment]::GetEnvironmentVariable("PATH", "Machine") + ";" + 
                      [System.Environment]::GetEnvironmentVariable("PATH", "User")
          
          # Проверка доступности ключевых инструментов
          cmake --version
          msbuild /version

      # 3. Установка VST3 SDK
      - name: Setup VST3 SDK
        shell: pwsh
        run: |
          if (!(Test-Path "externals/VST3_SDK")) {
            New-Item -ItemType Directory -Path "externals" -Force | Out-Null
            git clone --recursive https://github.com/steinbergmedia/vst3sdk.git externals/VST3_SDK
          }

      # 4. Конфигурация CMake
      - name: Configure CMake
        shell: pwsh
        run: |
          cmake -B build `
            -DCMAKE_BUILD_TYPE=Release `
            -DJUCE_DIR="${{ github.workspace }}\externals\JUCE" `
            -DVST3_SDK_DIR="${{ github.workspace }}\externals\VST3_SDK"

      # 5. Сборка плагина
      - name: Build
        run: cmake --build build --config Release --target DroneSynth_VST3

      # 6. Загрузка артефактов
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DroneSynth_Windows
          path: |
            build/DroneSynth_artefacts/Release/VST3/DroneSynth.vst3
            build/DroneSynth_artefacts/Release/Standalone/DroneSynth.exe
